ENV_KEYS = [
    "ANYTHINGLLM_BASE_URL",
    "ANYTHINGLLM_API_KEY",
    "ANYTHINGLLM_TIMEOUT_SECONDS",
    "ANYTHINGLLM_MAX_RETRIES",
    "EXTRACTOR_BASE_URL",
    "EXTRACTOR_API_KEY",
    "EXTRACTOR_TIMEOUT_SECONDS",
    "EXTRACTOR_MAX_RETRIES",
]
