from rfp.prompts import (
    RESEARCH_BUDGET_PROMPT,
    RESEARCH_FALLBACK_BUDGET,
    RESEARCH_FALLBACK_SCOPE,
    RESEARCH_QUERY_BASE,
    RESEARCH_QUERY_BUDGET_CLAUSE,
    RESEARCH_QUERY_GUARDRAILS,
    RESEARCH_QUERY_SELECTION_METHOD_CLAUSE,
    RESEARCH_SCOPE_PROMPT,
)

__all__ = [name for name in globals() if name.startswith("RESEARCH_")]
