ENV_KEYS = [
    "QUALITY_MIN_GROUNDEDNESS",
    "QUALITY_MIN_COHERENCE",
    "QUALITY_EVIDENCE_MAX_CHARS",
    "QUALITY_DRAFT_MAX_CHARS",
    "QUALITY_MAX_TOKENS",
    "QUALITY_LLM_MODEL",
    "LLM_GUARD_ENABLED",
]
